language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g swagger-cli

script:
  - swagger-cli validate swagger.yml

notifications:
  email:
    on_success: never