language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g swagger-cli
  - npm install -g yaml-lint

script:
  - yamllint swagger.yml
  - swagger-cli validate swagger.yml

notifications:
  email:
    on_success: never
